repos:
  # --- Python Code Quality ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.13

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: Sort imports
        language_version: python3.13

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        name: Lint with flake8
        additional_dependencies: [flake8-bugbear]
        args:
          - --max-line-length=88
          - --extend-ignore=E203,W503,E501

  - repo: local
    hooks:
      - id: update-requirements
        name: Ensure requirements.txt matches Poetry environment
        entry: poetry
        language: system
        args:
          - export
          - -f
          - requirements.txt
          - --without-hashes
          - -o
          - requirements.txt
        pass_filenames: false
        always_run: true
